# Generated by Django 4.0.4 on 2022-04-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allergie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='contreIndication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contreIndications', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroFiche', models.BigIntegerField(default=0)),
                ('dateNaissaince', models.DateField()),
                ('noms', models.CharField(blank=True, max_length=200)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(max_length=12)),
                ('telephone', models.BigIntegerField()),
                ('adresse', models.TextField(blank=True)),
                ('email', models.CharField(max_length=25)),
                ('dateArrive', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='rdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('observation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poidsA', models.CharField(blank=True, max_length=50)),
                ('poidsN', models.CharField(blank=True, max_length=50)),
                ('taille', models.CharField(blank=True, max_length=10)),
                ('temperature', models.CharField(default=0, max_length=10)),
                ('pressionArterielle', models.CharField(max_length=15)),
                ('battementCardiaque', models.CharField(blank=True, max_length=15)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=200)),
                ('sexe', models.CharField(max_length=12)),
                ('telephone', models.BigIntegerField()),
                ('adresse', models.TextField(blank=True)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
